-- AlterTable
ALTER TABLE "Trip" ADD COLUMN     "billNumber" TEXT,
ADD COLUMN     "charges" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "customerAdvance" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "customerDiesel" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "damageAmount" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "damageNotes" TEXT,
ADD COLUMN     "gcBalance" DOUBLE PRECISION,
ADD COLUMN     "tds" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "transporter" TEXT;
